server:
  port: 8002
spring:
  application:
    name: 002-eureka-client-consumer
  redis:
    port: 6379
    host: localhost
    database: 0
eureka:
  client:
    service-url:
        defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
feign:
  hystrix:
    enabled: true   # 文件中没有提示，不影响
