server:
  port: 5002
spring:
  application:
    name: 004-GateWay
  cloud:
    gateway:
      routes:
        - id: tobaidu
          predicates:
              - Path=/
          uri: https://www.baidu.com

        - id: tobaidunews
          predicates:
            - Path=/consumer/**,/user/**
#          uri: http://localhost:8002
          uri: lb://002-EUREKA-CLIENT-CONSUMER
          filters:
#             #负载均衡
#            - name: RequestRateLimiter
#              args:
#                #每秒请求的次数
#                redis-rate-limiter.replenishRate: 5
#                #桶的容量
#                redis-rate-limiter.burstCapacity：: 3
#                key-resolver: "#{@userKeyResolver}"
  redis:
    host: localhost
    port: 6379
    database: 0




eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka