server:
  port: 8001
spring:
  application:
  redis:
    port: 6379
    host: localhost
    database: 0
    #注册到注册中心的微服务名称
    name: 002-eureka-client-consumer
eureka:
  instance:
    #超时后剔除列表的时间
    lease-expiration-duration-in-seconds: 80
    #心跳交互的时间
    lease-renewal-interval-in-seconds: 80
  client:
    service-url:
      #注册中心的地址
      #这里配置多个节点的意义是如果6001故障的话那么6002还可以连接
      defaultZone: http://localhost:6001/eureka,httpl://localhost:6002/eureka
management:
  endpoints:
    web:
      #健康检查的默认根路径地址，默认是acturtor
      base-path: /acturtor
      exposure:
        #健康检查开放的端点，默认是info、health
        include: 'health'